### ISSUE TITLE
View Component markup not minified

### ISSUE THREAD

**Issue by J3-code** [Taritsyn/WebMarkupMin#101]
I recently noticed that when I include a view component in my Razor page, the content of the page is not minified.

Is this behavior expected? If so, is there any way to minify the View Component output? In my specific case the component is being rendered/called recursively, and is generating a fair amount of markup that would benefit from minification.

Version: WebMarkupMin.AspNetCore3 (2.7.0)

**Comment by Taritsyn** [comment]
Hello, James!

Honestly, I have not tested this behavior yet. When I have free time, I will definitely check this.

> …, the content of the page is not minified.

It is also possible that the View Component contains invalid markup.

In the `Startup.cs` file set a `ThrowExceptionLogger` as the default logger in order to see parsing errors:

```csharp
…
using IWmmLogger = WebMarkupMin.Core.Loggers.ILogger;
using WmmThrowExceptionLogger = WebMarkupMin.Core.Loggers.ThrowExceptionLogger;

namespace WebMarkupMin.Sample.AspNetCore3.Mvc3
{
    public class Startup
    {
        …
        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            …
            // Override the default logger for WebMarkupMin.
            services.AddSingleton<IWmmLogger, WmmThrowExceptionLogger>();
            …
        }
        …
    }
}
```

In the future I recommend to you using own implementation of logger (see the [“Loggers”](https://github.com/Taritsyn/WebMarkupMin/wiki/Loggers) section of documentation) instead of the `ThrowExceptionLogger`.

**Comment by J3-code** [comment]
Well, I feel like a goof. WMM is indeed throwing a `MarkupParsingException`.

As I mentioned, this component calls itself recursively to render a complicated hierarchy, which the browser kindly renders without pointing out whatever markup flaws may be present.

I'm terribly sorry for wasting your time. Thanks for pointing me in the right direction.

**Comment by Taritsyn** [comment]
It's alright. This is a fairly common problem.
