### ISSUE TITLE
Tiny "bug" (or edge case bug)

### ISSUE THREAD

**Issue by Sausbolle** [Taritsyn/WebMarkupMin#107]
If you have nested `<!--wmm:ignore--> .... <!--/wmm:ignore-->` it will break WebMarkupMin and nothing is minimized. Easy to get around with some alteration (in my case) but there might be cases where it is beneficial for WebMarkupMin to soldier on and minimize even if there is nested ignore markups.

Ex (this will break the minimization of the html and nothing is minimized):
```
<!--wmm:ignore-->
Some text to
  not remove spaces and lineshifts from
    <!--wmm:ignore-->
      That happens to have an ignore block
          inside itself
    <!--/wmm:ignore-->
<!--/wmm:ignore-->
```

**Comment by Taritsyn** [comment]
Hello!

Ignoring comment tags are called ignoring, because they do not analyze (parse) their contents. Your example is mistaken in essence, because it makes no sense to enclose ignoring comment tags in each other.

Add a custom logger (or at least `ThrowExceptionLogger`) to the ASP.NET extension, that you use in your project, and you will see an error message like this:

```
Line 8, Column 1: HTML_PARSING_ERROR. It is impossible to parse a end ignoring comment tag, because not declared the start ignoring comment tag.

Line 7:     <!--/wmm:ignore-->
Line 8: <!--/wmm:ignore-->
--------^
```

**Comment by Sausbolle** [comment]
Thanks for clarification.

The reason I got the "error" was because I did some custom markup (bbcode style) that had some blocks that needed to be kept un-minimized, and in some cases those became nested. When turning the bbcode style text into html (also adding ignore tags) to be added to Razor pages the nesting of the ignore tags happened. But I found a workaround for it so the nesting of "ignore tags" didn't occur anymore.
