### ISSUE TITLE
Does not affect all controllers

### ISSUE THREAD

**Issue by parsintalk** [Taritsyn/WebMarkupMin#118]
Hello.
I used WebMarkupMin in a .net core 3.1 project.
Unfortunately, only the views of the home controller are minified and other controllers do not change.
Can you guide me to minify all the views?
With a lot of thanks.

**Comment by Taritsyn** [comment]
Hello!

It is possible that other pages contain a HTML syntax error.

In the `Startup.cs` file set a `ThrowExceptionLogger` as the default logger in order to see parsing errors:

```csharp
…
using IWmmLogger = WebMarkupMin.Core.Loggers.ILogger;
using WmmThrowExceptionLogger = WebMarkupMin.Core.Loggers.ThrowExceptionLogger;

namespace WebMarkupMin.Sample.AspNetCore3.Mvc3
{
    public class Startup
    {
        …
        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            …
            // Override the default logger for WebMarkupMin.
            services.AddSingleton<IWmmLogger, WmmThrowExceptionLogger>();
            …
        }
        …
    }
}
```

In the future I recommend to you using own implementation of logger (see the [“Loggers”](https://github.com/Taritsyn/WebMarkupMin/wiki/Loggers) section of documentation) instead of the `ThrowExceptionLogger`.
