### ISSUE TITLE
Tailwind Class-names are being destroyed by this framework..

### ISSUE THREAD

**Issue by Montago** [Taritsyn/WebMarkupMin#120]
TailwindCSS uses a 'creative' naming scheme for their classnames. 

eg "w-1/3" which is width:33%;

when using WebMarkupMin, the slash is removed from the html

eg:
`<div class="w-1/3">.. becomes <div class="w-1 3">`

**Comment by Taritsyn** [comment]
Hello, Montago!

A similar error ([“Minification of html class attributes with slashes”](https://github.com/Taritsyn/WebMarkupMin/issues/115)) has already been fixed in [version 2.8.6](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.8.6).

Update the WebMarkupMin.Core package to latest version. If this package is not in the list of dependencies, then install it.

**Comment by Montago** [comment]
thanks !
