### ISSUE TITLE
Hmmm… can't reach this page It looks like the webpage

### ISSUE THREAD

**Issue by HashemGo** [Taritsyn/WebMarkupMin#152]
After upgrade to .NET 7
I used `using WebMarkupMin.AspNetCore7`

all projects stop working, I hope to help me as an emergency

**Browser Error**
_Hmmm… can't reach this page It looks like the webpage at https://localhost:****/ might be having issues, or it may have moved permanently to a new web address.
ERR_HTTP2_PROTOCOL_ERROR_

**Log Error details**
`2022-11-21T11:02:57.9975051+02:00 40000059-0002-fb00-b63f-84710c7967bb [WRN] Unable to configure browser refresh script injection on the response. This may have been caused by the response's Content-Encoding: '["br"]'. Consider disabling response compression. (01be8070)`

**Comment by Taritsyn** [comment]
Hello, Hashem!

Why do you think that the `ERR_HTTP2_PROTOCOL_ERROR` error is caused by the WebMarkupMin Middleware? Try disabling a WebMarkupMin Middleware and see if this error occurs without it. If this error still occurs, then I recommend to you use recommendations from the [“How To Fix the ERR_HTTP2_PROTOCOL_ERROR”](https://kinsta.com/knowledgebase/err_http2_protocol_error/) article.

Regarding the following warning:

```
warn: Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware[4]
      Unable to configure browser refresh script injection on the response. This may have been caused by the response's Content-Encoding: 'br'. Consider disabling response compression.
```

Text of this warning means that the Browser Link or Hot Reload cannot fully work when HTTP compression is enabled. Just disable markup minification and HTTP compression during development:

```csharp
builder.Services.AddWebMarkupMin(options =>
{
	options.AllowMinificationInDevelopmentEnvironment = false;
	options.AllowCompressionInDevelopmentEnvironment = false;
})
…
```

By the way, this warning is also issued when the [Response Compression Middleware](https://learn.microsoft.com/en-us/aspnet/core/performance/response-compression) that developed by Microsoft is enabled.
