### ISSUE TITLE
WebMarkupMin always minify even if disabled

### ISSUE THREAD

**Issue by ghost** [Taritsyn/WebMarkupMin#26]
Hello Taritsyn,

Happy New Year!
I am using the latest packages below in my ASP.NET MVC project.

WebMarkupMin.AspNet.Common	2.2.5.0
WebMarkupMin.AspNet4.Common	2.2.2.0
WebMarkupMin.AspNet4.Mvc	2.2.2.0
WebMarkupMin.Core	2.2.4.0
WebMarkupMin.MsAjax	2.2.0.0
WebMarkupMin.Yui	2.2.0.0

I usually configure minifer by adding the following line in Application_Start().

  WebMarkupMinConfig.Configure(WebMarkupMinConfiguration.Instance);

Today, I noticed that the minifier always be executed even though I disabled it by removed the above line from Application_Start().

I tried several tests and found that minifier seems working by using the following default config setting.
https://github.com/Taritsyn/WebMarkupMin/blob/master/samples/WebMarkupMin.Sample.AspNet4.Mvc4/App_Start/WebMarkupMinConfig.cs

This symptom happens only for Release mode.
If you can reproduce the problem, please fix it.

**Comment by ghost** [comment]
Taritsyn,
Sorry, problem was solved.
I created a new MVC project again and installed your  WebMarkupMin packages.
Everything works fine.
So, something was wrong in my old MVC project.
But, I do not know why the strange symptom I reported happened.
If you can guess the reason, please let me know.
In my test, 
I had run clean build many times and remove bin and obj folders also.
But problem was not solved.
Anyway, now everything works fine.

**Comment by Taritsyn** [comment]
Hello, Hiromi!

Thanks for your greetings with New Year.

Removing of this line:

```csharp
WebMarkupMinConfig.Configure(WebMarkupMinConfiguration.Instance);
```

does not disable a markup minification. This leads to the fact, that instead of your custom settings will use the default settings.

To disable a markup minification you need to use properties of `WebMarkupMinConfiguration` class. Moreover, behavior of some configuration properties depends on the web application mode (debug or release).

I recommend you to read carefully the following sections of documentation: [“ASP.NET Extensions”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-Extensions), [“ASP.NET 4.X Extensions”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-Extensions) and [“WebMarkupMin: ASP.NET 4.X MVC”](https://github.com/Taritsyn/WebMarkupMin/wiki/WebMarkupMin:-ASP.NET-4.X-MVC).

**Comment by ghost** [comment]
Taritsyn,
Thank you for the detailed answer.
By your answer, I could understand what was wrong.
I will read the documents you recommeneded to me.
