### ISSUE TITLE
Why HTML minimizer encode & to &amp; ?

### ISSUE THREAD

**Issue by rizs** [Taritsyn/WebMarkupMin#69]
Hello!

Could you please look why HTML minimizer encode for example & to `&amp;` ? I found this in links, but still encode all simbols too.

For example i have this link:
`<a href="{domain}/s?q=hotel&c=m%C3%BCnchen&z=&p=1&dst=&sUrl=&cUrl=Muenchen">`
will be after HTML minimizer this:
`<a href="{domain}/s?q=hotel&amp;c=m%C3%BCnchen&amp;z=&amp;p=1&amp;dst=&amp;sUrl=&amp;cUrl=Muenchen">`

or for copyright sign: `Copyright &#xA9; 2001 - 2018`

I see that all site which it's mentioned that use this HTML minimizer has this same "problem", I don't know, this it's a bug, WebMarkupMin has an option flag to set this or there will be no problem about this? For example some version of browsers doesn't support or Google bots can't decode the url?

Thank you for taking a look about this!

**Comment by Taritsyn** [comment]
Hello!

Your link does not work.

> For example some version of browsers doesn't support or Google bots can't decode the url?

There is no problem, because this code conforms to the standards. You can check the following code:

```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Some title</title>
	</head>
	<body>
		<h1>Heading</h1>
		<p><a href="http://example.com/api?opt=value&amp;opt2=value2">Some text...</a></p>
	</body>
</html>
```

by using the [W3C Markup Validation Service](https://validator.w3.org/#validate_by_input).

I know that in HTML can use `&` instead of `&amp;` in attribute values. Just now, the same algorithm is used to process attribute values for HTML and XHTML. In the future, I will change this functionality.

**Comment by rizs** [comment]
Ok, Thank you for your answer! :)
