### ISSUE TITLE
Minification of kendo templates

### ISSUE THREAD

**Issue by NePheus** [Taritsyn/WebMarkupMin#70]
Kendo (by Telerik) uses script-tags to bind data to HTML-Templates.
(see here [https://docs.telerik.com/kendo-ui/framework/templates/overview](url))
Example:
```
<script id="javascriptTemplate" type="text/x-kendo-template">
    <div>...</div>
</script>
```
When enabling the WebMarkupMin JsMinifier, this script-tag is not being minified. When I remove the "type" attribute, it does minify this code, but I get Visual Studio syntax errors.

Is there a way to get the minifier work with the _type="text/x-kendo-template"_ attribute?

**Comment by Taritsyn** [comment]
Hello, Jan!

> When enabling the WebMarkupMin JsMinifier, this script-tag is not being minified. 

JS minifiers are not designed to process templates. Templates are usually minified by using an HTML minifier. To do this, use the `ProcessableScriptTypeList` property (see the [“HTML Minifier”](https://github.com/Taritsyn/WebMarkupMin/wiki/HTML-Minifier) section of documentation).

But in this case, I do not recommend doing this, because modern the [Kendo UI Templates](https://docs.telerik.com/kendo-ui/framework/templates/overview) are no longer based on DOM and the WebMarkupMin will not be able to process them. WebMarkupMin only supports the old Knockout-based template syntax ([Kendo UI MVVM](https://docs.telerik.com/kendo-ui/framework/mvvm/overview)).

**Comment by NePheus** [comment]
Thank you very mich for the clarification!
