### ISSUE TITLE
Stopped working when upgraded from .net 4.5 to 4.62

### ISSUE THREAD

**Issue by christopherdude** [Taritsyn/WebMarkupMin#81]
Hi Taritsyn,

First, thank you for this wonderful code.  It worked well for me for quite a while, however after seemingly upgrading from .Net 4.5 to 4.62 (not sure if that's what caused it), it stopped all compression and minification.  So I moved the application back to 4.5, and I still can't get it to minify.  I've attempted both DEBUG=false in the config as well as 
			configuration.AllowMinificationInDebugMode = true;
			configuration.AllowCompressionInDebugMode = true;
but nothing seems to work.  I'm receiving no errors, and can confirm it's the same code I've been using all along.  

I really appreciate any insights you may have?

**Comment by Taritsyn** [comment]
Hello, Christopher!

Which ASP.NET extension do you use in the web application: WebMarkupMin.AspNet4.HttpModules, 
WebMarkupMin.AspNet4.Mvc or WebMarkupMin.AspNet4.WebForms?

**Comment by Taritsyn** [comment]
I checked compatibility of the WebMarkupMin.AspNet4.WebForms module with .NET Framework 4.62. Everything works correctly for me. It seems that the problem is something else.

I suggest the following action plan:

 1. Check the correctness of settings in the `App_Start/WebMarkupMinConfig.cs` and `Global.asax.cs` files (see the [“ASP.NET 4.X Extensions”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-Extensions) section of documentation).
 1. Check the plugging of the WebMarkupMin.AspNet4.WebForms module (see the [“ASP.NET 4.X Web Forms”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-Web-Forms) section of documentation).
1. In the `App_Start/WebMarkupMinConfig.cs` file set a `ThrowExceptionLogger` as the default logger in order to see parsing errors:

```csharp
…
using WebMarkupMin.AspNet4.Common;
…
using WebMarkupMin.Core.Loggers;
…

    public class WebMarkupMinConfig
    {
        public static void Configure(WebMarkupMinConfiguration configuration)
        {
            …
            DefaultLogger.Current = new ThrowExceptionLogger();
            …
        }
    }
}
```

If none of this helps, then try to reproduce the error in form of a demonstration project.

**Comment by christopherdude** [comment]
You’re a genius.  I’m glad you put that error flag in there.  What was happening was, my code was producing bad escape characters in an unrelated section (meta tags).  It seems strange that your code would choke on that, but this flag is GREAT.  THANK YOU!  Kudos to your great programming here.

**Comment by Taritsyn** [comment]
In the future I recommend to you using own implementation of logger (see the [“Loggers”](https://github.com/Taritsyn/WebMarkupMin/wiki/Loggers) section of documentation) instead of the `ThrowExceptionLogger`.

**Comment by Taritsyn** [comment]
By the way, if you update the WebMarkupMin.Core module to version 2.5.7, you can minify the contents of `script` tags with `application/ld+json` type.

**Comment by christopherdude** [comment]
What's the setting to do that? You're awesome
________________________________

**Comment by Taritsyn** [comment]
`MinifyEmbeddedJsonData` (default `true`). This setting appeared in [version 2.5.7](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.5.7).
