### ISSUE TITLE
Multiple MarkupMin Configuration Support?

### ISSUE THREAD

**Issue by aloksharma1** [Taritsyn/WebMarkupMin#92]
hello,

i have a case where we have an admin side and a frontend site for our users, i want to control if user side is minified on not from admin side. but dont want to turn off minification/compression for admin end. is it possible to use two different config files and control the behavir for users?

```
WebMarkupMinConfig.Configure(WebMarkupMinConfiguration.Instance);
MarkupMinSite.Configure(WebMarkupMinConfiguration.Instance);
```
i put this in global.asax as per the example given in mvc4 project sample, but the last config takes effect. is this separation possible?

thanks

**Comment by Taritsyn** [comment]
Hello, Alok!

WebMarkupMin configuration applies to the entire web application. In this case, you have admin side and a frontend site in one web application.

Divide the sides into two web applications.

**Comment by aloksharma1** [comment]
due to the complexity of project i cant do that, i think i will just download the library code and change all names to markupmin2 recompile & use as second instance? will this work in theory?

**Comment by Taritsyn** [comment]
This will not work because the WebMarkupMin ASP.NET extensions initially work at the level of entire web application.

You can simply exclude entire sections of web application from processing by using the `IncludedPages` or `ExcludedPages` configuration properties (see the [“ASP.NET Extensions > Managers and options”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-Extensions#managers-and-options) subsection of documentation).

**Comment by aloksharma1** [comment]
nice, this is exactly what i needed.
thanks
