### ISSUE TITLE
troubleshooting options?

### ISSUE THREAD

**Issue by c9mb** [Taritsyn/WebMarkupMin#94]
5 sites with WebMarkupMin installed - 2 working as expect, 3 not minifying at all.

All 5 sites have the same code (comparison tool confirmed) and the WebMarkupMin is the same on all 5. The only differences in the sites are css and cms-content.

What troubleshooting options are available so I can find the cause of the problem on the 3 sites that are not minifying?

**Comment by Taritsyn** [comment]
Hello, Mike!

What WebMarkupMin ASP.NET extension you use?

**Comment by c9mb** [comment]
Hi,

It's been a while since I installed it on my master site (which I copy to new sites) but I think it was WebMarkupMin.Core and WebMarkupMin.AspNet4.Mvc and WebMarkupMin.Yui

**Comment by Taritsyn** [comment]
In the `App_Start/WebMarkupMinConfig.cs` file set a `ThrowExceptionLogger` as the default logger in order to see parsing errors:

```csharp
…
using WebMarkupMin.AspNet4.Common;
…
using WebMarkupMin.Core.Loggers;
…

    public class WebMarkupMinConfig
    {
        public static void Configure(WebMarkupMinConfiguration configuration)
        {
            …
            DefaultLogger.Current = new ThrowExceptionLogger();
            …
        }
    }
}
```

In the future I recommend to you using own implementation of logger (see the [“Loggers”](https://github.com/Taritsyn/WebMarkupMin/wiki/Loggers) section of documentation) instead of the `ThrowExceptionLogger`.

**Comment by c9mb** [comment]
Cheers.
